version: 2

updates:
# Terraform - One entry per thing we want to scan as per https://github.com/dependabot/dependabot-core/issues/649
  - package-ecosystem: "terraform"
    directory: "/modules/delivery_configuration"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/modules/target"
    schedule:
      interval: "weekly"
